[package]
name = "notify-app"
version = "0.1.0"
authors = ["muhammadtaqi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify_lib = { path = "../notify-lib" }